### ISSUE TITLE
Anchors disappearing

### ISSUE THREAD

**Issue by nagim** [atuttle/gitbook-plugin-heading-anchors#2]
Hi,

I just tried out this plugin, like it much better than other plugins available for gitbook.
However, I noticed that first it shows when I open the book, but if I navigate to another chapter, the anchors no longer appearing, I have to refresh the browser for them to reappear.

Many thanks if you have a look at this.

Cheers,
Imre

**Comment by atuttle** [comment]
Ooh good catch! I will take a look at this asap.

**Comment by atuttle** [comment]
@nagim version 1.0.2 of the plugin should address this. Thanks for the report!

**Comment by nagim** [comment]
Thanks for the quick fix, I will check it out soon!

**Comment by nagim** [comment]
It appears to be working, the only small thing I noticed is that at the first load of the page, it displays two anchors. If I navigate to another page, it's fine

**Comment by atuttle** [comment]
Interesting! I think I know what's causing that. 1.0.3 will be out shortly with a fix...

**Comment by atuttle** [comment]
Try now with 1.0.3?

**Comment by nagim** [comment]
Sorry, I could only test it now. It works fine, great work! :clap: 
Thanks!

P.S.:
One more question: do you think you could also implement paragraph anchors? Maybe make it as an option, using pluginsconfig? Just an idea.
Thanks a lot!

**Comment by atuttle** [comment]
Adding configuration is something I want to do (see: #1) but don't have time to dive into just yet.

Are you saying you want to be able to link to each paragraph, too?

**Comment by nagim** [comment]
I see some cases, when it could be useful, I think. 

For me, it's the ability to link to a specific paragraph without the need of creating a heading for it.

In general, I guess it's not a widely wanted feature, that's why I thought it shouldn't be enabled by default, but make is optional instead. I saw examples for that on the anchor.js site, I thought it could be done without much hassle. But I understand if you don't have time for it.

The configuration idea is great (but I'm also happy with the current style :smile:).
